version: '3.7'
services:
    dbpg:
        image: postgis/postgis
        restart: always
        environment:
          - POSTGRES_DATABASE=dbpa
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - 5432:5432
        volumes:
          - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql        
    node:
        build: .
        restart: always
        ports:
          - 3000:3000
        environment:
          - POSTGRES_DATABASE=dbpa
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_HOST=dbpg
          - POSTGRES_PORT=5432
        env_file:
          - .env
        depends_on:
          - dbpg